version: '3.8'
services:
# APP SERVICE
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    environment:
      -RAILS_ENV: production
    depends_on:
      - db
    networks:
      - app_network

# MYSQL SERVICE
  db:
    image: "mysql:5.7"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redmine
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

# NGINX SERVICE
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/redmine
    depends_on:
      - app
      - db
    networks:
      - app_network
networks:
  app_network:

volumes:
  mysql_data:
